### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by remsrc** [retconx/scoregdt#1]
First start of program works fine. Without a license, the program runs into an exception in the module gdttoolL.

**Comment by retconx** [comment]
To run ScoreGDT without a licence key the code lines between _## Nur mit Lizenz_ and _## /Nur mit Lizenz_ in _main.py_ need to be deleted:

`\#\# Nur mit Lizenz

Delete
these
lines

\#\# /Nur mit Lizenz`
