### ISSUE TITLE
wrong representation after implementing gender and age rule

### ISSUE THREAD

**Issue by remsrc** [retconx/scoregdt#2]
With the new "Marburger Herz-Score" all other scores have wrong checkbutton values. Please only set/unset other checkbuttons in a \<part\>, when you have the gender+age rule.
```    
main.py (l 511)                       
# Wenn RadioButton, andere Buttons unchecken
if "_" in regel:
    for w in self.widgets:
       if w.getId() != widget.getId() and w.getPartId() == widget.getPartId():
            w.getQt().setChecked(not regelnErfuellt)
```

**Comment by retconx** [comment]
Thanks for reporting this issue!
(Un)setting is only done in RadioButtons of one dedicated part, now.
