### ISSUE TITLE
MacOS Release

### ISSUE THREAD

**Issue by LordMyschkin** [retconx/scoregdt#3]
Auf einem aktuellen MacOS M2-Mb Air kann die App nicht gestartet werden, weil das OS nicht nach Schadsoftware in der App suchen kann.

Ich finde die Initiative übrigens super!!

**Comment by retconx** [comment]
Danke für die Rückmeldung!
So sollte es funktionieren:
- Die Zip-Datei GeriGDT.app.zip durch Doppelklick entpacken
- Das entpackte Bundle GeriGDT.app in den Programme-Ordner kopieren
- Dort mit gedrückter Control-Taste auf GeriGDT.app klicken und im Contextmenü ganz oben auf Öffnen klicken
- Im folgenden Dialogfeld auf Öffnen klicken
